"""Ollama Local LLM Service for Air-Gapped Generation and Reasoning.

Enables local GPU/CPU inference via Ollama without any cloud telemetry or egress.
Integrates with the Hard Citation Contract: all claims generated by the LLM
are parsed into sentences and strictly bound to source chunk offsets by CitationLinker.
"""

import logging
import re
from typing import Any

import httpx

from app.core.config import get_settings

logger = logging.getLogger("app.services.llm.ollama")
settings = get_settings()


class OllamaService:
    """Async client managing local inference with Ollama daemon."""

    _instance: "OllamaService | None" = None

    def __init__(self) -> None:
        self.base_url = settings.OLLAMA_BASE_URL.rstrip("/")
        self.default_model = settings.OLLAMA_MODEL
        self.timeout = settings.OLLAMA_TIMEOUT

    @classmethod
    def get_instance(cls) -> "OllamaService":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    async def is_available(self, timeout: float = 1.0) -> bool:
        """Check if local Ollama daemon is reachable and responding."""
        if not settings.OLLAMA_ENABLED:
            return False
        try:
            async with httpx.AsyncClient(timeout=timeout) as client:
                res = await client.get(f"{self.base_url}/api/tags")
                return res.status_code == 200
        except Exception:
            return False

    async def list_models(self) -> list[str]:
        """Fetch list of available model names from local Ollama library."""
        try:
            async with httpx.AsyncClient(timeout=2.0) as client:
                res = await client.get(f"{self.base_url}/api/tags")
                if res.status_code == 200:
                    data = res.json()
                    return [m.get("name", "") for m in data.get("models", [])]
        except Exception as exc:
            logger.debug("Failed to list Ollama models: %s", exc)
        return []

    def clean_llm_output(self, text: str) -> str:
        """Remove <think>...</think>, analytical scratchpad notes, and Thinking Process traces."""
        if not text:
            return ""
        cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
        cleaned = re.sub(r"<think>.*", "", cleaned, flags=re.DOTALL)
        cleaned = re.sub(r"<thought>.*?</thought>", "", cleaned, flags=re.DOTALL)
        cleaned = re.sub(r"^\s*/no_think\s*", "", cleaned, flags=re.IGNORECASE)

        # Strip common reasoning preambles from DeepSeek / Qwen MTP models
        markers = [
            r"\bFinal\s+Answer:\s*",
            r"\bDeliverable:\s*",
            r"\bOutput:\s*",
            r"\bResponse:\s*",
            r"\bDraft:\s*",
            r"\bPost:\s*",
            r"\bGenerated\s+Deliverable:\s*",
        ]
        for m in markers:
            parts = re.split(m, cleaned, flags=re.IGNORECASE)
            if len(parts) > 1 and len(parts[-1].strip()) > 20:
                cleaned = parts[-1]
                break

        if re.search(r"thinking process:", cleaned, re.IGNORECASE):
            parts = re.split(r"(?:Final Answer:|Deliverable:|Output:|Response:|\n\n---\n\n|\n\n\n+)", cleaned, flags=re.IGNORECASE)
            if len(parts) > 1 and len(parts[-1].strip()) > 20:
                cleaned = parts[-1]
            else:
                cleaned = re.sub(r"^(?:#*\s*Thinking Process:?|Thinking:?).*?(?=\n\n[A-Z]|\Z)", "", cleaned, flags=re.DOTALL | re.IGNORECASE)

        return cleaned.strip()

    async def generate_text(
        self,
        prompt: str,
        system_prompt: str | None = None,
        model_name: str | None = None,
        temperature: float = 0.15,
        max_tokens: int = 1024,
    ) -> str | None:
        """Generate text using local Ollama model with grounding constraints.

        Returns cleaned response text, or None if Ollama is unreachable.
        """
        import time

        if not settings.OLLAMA_ENABLED:
            return None

        target_model = model_name or self.default_model

        payload: dict[str, Any] = {
            "model": target_model,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": temperature,
                "num_predict": max_tokens,
                "num_ctx": 4096,
                "top_k": 20,
                "top_p": 0.9,
            },
        }
        if system_prompt:
            payload["system"] = system_prompt

        start_t = time.time()
        logger.info("[Ollama] Initiating local inference with model: %s (max_tokens=%d)", target_model, max_tokens)
        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                res = await client.post(f"{self.base_url}/api/generate", json=payload)
                dur = time.time() - start_t
                if res.status_code == 200:
                    raw_response = res.json().get("response", "")
                    cleaned = self.clean_llm_output(raw_response)
                    logger.info("[Ollama] Inference succeeded in %.2fs (%d chars) using %s", dur, len(cleaned), target_model)
                    return cleaned
                else:
                    logger.warning("[Ollama] Returned status %d in %.2fs: %s", res.status_code, dur, res.text)
        except httpx.TimeoutException:
            dur = time.time() - start_t
            logger.warning("[Ollama] Inference timed out after %.1fs for model %s", dur, target_model)
        except Exception as exc:
            logger.debug("[Ollama] Generation failed (%s), falling back to deterministic synthesis.", exc)

        return None

    async def extract_text_from_image(
        self,
        image_bytes: bytes,
        prompt: str = (
            "Analyze the provided image and extract its substantive content:\n"
            "- If the image is a document, scan, diagram, screenshot, or slide containing text: transcribe all text, headings, data, and tables verbatim preserving structure.\n"
            "- If the image is a photograph, scene, portrait, or visual media without document text: provide a clear, factual description of what is depicted, including people, objects, setting, and any visible labels or insignia.\n"
            "Output the extracted text or factual description directly without conversational preamble."
        ),
        max_tokens: int = 2048,
    ) -> str | None:
        """Execute local Vision OCR and visual content extraction using Qwen3-VL model via Ollama."""
        import base64
        import io
        from PIL import Image

        if not settings.OLLAMA_ENABLED:
            return None

        # Resize image if excessively large to keep inference fast and crisp
        try:
            stream = io.BytesIO(image_bytes)
            img = Image.open(stream)
            if img.mode not in ("RGB", "L"):
                img = img.convert("RGB")
            # Max dimension 1280px while preserving aspect ratio
            max_dim = 1280
            if max(img.size) > max_dim:
                img.thumbnail((max_dim, max_dim), Image.Resampling.LANCZOS)
            out_buf = io.BytesIO()
            img.save(out_buf, format="JPEG", quality=85)
            b64_data = base64.b64encode(out_buf.getvalue()).decode("utf-8")
        except Exception as exc:
            logger.warning("Failed to prepare image for vision OCR: %s", exc)
            b64_data = base64.b64encode(image_bytes).decode("utf-8")

        target_model = settings.OLLAMA_VISION_MODEL or self.default_model

        payload = {
            "model": target_model,
            "prompt": prompt,
            "images": [b64_data],
            "stream": False,
            "options": {
                "num_ctx": 4096,
                "temperature": 0.1,
                "num_predict": max_tokens,
            },
        }

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                res = await client.post(f"{self.base_url}/api/generate", json=payload)
                if res.status_code == 200:
                    raw_text = res.json().get("response", "")
                    cleaned = self.clean_llm_output(raw_text)
                    logger.info("Vision OCR extracted %d chars using %s", len(cleaned), target_model)
                    return cleaned
                else:
                    logger.warning("Vision OCR failed with status %d: %s", res.status_code, res.text)
        except httpx.TimeoutException:
            logger.warning("Vision OCR timed out after %.1fs for model %s", self.timeout, target_model)
        except Exception as exc:
            logger.warning("Vision OCR inference failed via %s: %s", target_model, exc)

        return None


def get_ollama_service() -> OllamaService:
    """Dependency helper for global OllamaService singleton."""
    return OllamaService.get_instance()


async def check_ollama_health() -> dict[str, Any]:
    """Check Ollama connectivity, latency, and available models for health endpoint."""
    import time

    start = time.perf_counter()
    svc = get_ollama_service()
    available = await svc.is_available(timeout=2.0)
    latency = (time.perf_counter() - start) * 1000

    if available:
        models = await svc.list_models()
        return {
            "status": "healthy",
            "latency_ms": round(latency, 2),
            "endpoint": svc.base_url,
            "active_model": svc.default_model,
            "available_models": models,
        }
    return {
        "status": "disabled" if not settings.OLLAMA_ENABLED else "unreachable",
        "latency_ms": round(latency, 2),
        "endpoint": svc.base_url,
        "error": "Ollama daemon not responding or disabled",
    }
